config/routes.rb
Rails.application.routes.draw do
  #post '/profile' => 'users#index'
  post '/posts/search' => 'posts#search'
  resources :comments do
    member do
      put "like" => 'comments#upvote'
      put "dislike" => 'comments#downvote'
      put "unlike" => 'comments#upunvote'
      put "undislike" => 'comments#updownvote'
    end
  end

  devise_for :users
  resources :posts do
      	member do
  		put "like" => 'posts#upvote'
  		put "dislike" => 'posts#downvote'
      put "unlike" => 'posts#upunvote'
      put "undislike" => 'posts#updownvote'
  	end
      resources :comments
  end 

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
			validates :comment, exclusion: {in: %w(tangina amboy tanginamo taemo kantot putanginamo bakla bading beki batuta betlog bayot gago pakyo bobo potangina anal anus arse ass ballsack balls bastard bitch biatch bloody blowjob blow job bollock bollok boner boob bugger bum butt buttplug clitoris cock coon crap cunt damn dick dildo dyke fag feck fellate fellatio felching fuck f_u_c_k fudgepacker fudge packer flange Goddamn damn homo jerk jizz knobend knob end labia lmao lmfao muff nigger nigga omg penis piss poop prick pube pussy queer scrotum shit shit sh1t slut smegma spunk tit tosser turd twat vagina wank whore wtf), message: "%{value} is a profanity word. Invalid Comment!"}
	acts_as_votable
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :title, :content, exclusion: {within: %w(tangina amboy tanginamo taemo kantot putanginamo bakla bading beki batuta betlog bayot gago pakyo bobo potangina anal anus arse ass ballsack balls bastard bitch biatch bloody blowjob blow job bollock bollok boner boob bugger bum butt buttplug clitoris cock coon crap cunt damn dick dildo dyke fag feck fellate fellatio felching fuck f_u_c_k fudgepacker fudge packer flange Goddamn damn homo jerk jizz knobend knob end labia lmao lmfao muff nigger nigga omg penis piss poop prick pube pussy queer scrotum shit shit sh1t slut smegma spunk tit tosser turd twat vagina wank whore wtf), message: "%{value} is a profanity word. Invalid Post!"}
		acts_as_votable
		belongs_to :user
		has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :age, :department, :college, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save
		redirect_to post_path(@post)

	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

 	def upvote
  	  @comment = Comment.find(params[:id])
  	  @comment.upvote_by current_user
  	  redirect_to :back
	end

 	def downvote
  	  @comment = Comment.find(params[:id])
  	  @comment.downvote_by current_user
  	  redirect_to :back
 	end	

	def unupvote
	  @post = Comment.find(params[:id])
	  @post.unupvote_by current_user
	  redirect_to :back
	end

	def undownvote
	  @post = Comment.find(params[:id])
	  @post.undownvote_by current_user
	  redirect_to :back
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :find]

  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to :back
  end

  def unupvote
    @post = Post.find(params[:id])
    @post.unupvote_by current_user
    redirect_to :back
  end

  def undownvote
    @post = Post.find(params[:id])
    @post.undownvote_by current_user
    redirect_to :back
  end

  def search
    @posts = Post.where(title: params[:search_string])
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.comment %></p>
<strong>Commented <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %></strong>

      <br>
      <%= link_to like_comment_path(comment), method: :put, class: "btn btn-default btn-sm" do %>
        Upvote
        <%= comment.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_comment_path(comment), method: :put, class: "btn btn-default btn-sm" do %>
        Downvote
        <%= comment.get_downvotes.size %>
        <br>
      <% end %>

    <% if (user_signed_in? && (current_user.id == @post.user_id)) %>        
    <%= link_to "Edit Comment", edit_post_comment_path(comment.post, comment) %>
    <%= link_to "Delete Comment", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
<%= f.input :comment %>
<div class="form-group">
<%= f.submit "Submit", class: "btn btn-lg btn-default" %>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<p>Submitted <%= time_ago_in_words(@post.created_at) %> by <%= @post.user.name %></p>
      <br>
      <%= link_to like_post_path(@post), method: :put, class: "btn btn-default btn-sm" do %>
        Upvote
        <%= @post.get_upvotes.size %>
      <% end %>

      <%= link_to dislike_post_path(@post), method: :put, class: "btn btn-default btn-sm" do %>
        Downvote
        <%= @post.get_downvotes.size %>
        <% end %>
        <br>
  <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3>Reply to Thread</h3>
    <%= render "comments/form" %>

    <% if (user_signed_in? && (current_user.id == @post.user_id)) %>
      <%= link_to "Edit", edit_post_path(@post) %>
      <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?"} %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>COLLOQOUY</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= csrf_meta_tags %>
  </head>

  <body>
     <header class="navbar navbar-default" role="navigation">
        <div class="navbar-inner">
          <div class="container">
            <div id="logo" class="navbar-brand"><%= link_to "Colloqouy", root_path %> <p>"Network for Intelligent and Fair Discussion"</p></div>
             <nav class="collapse navbar-collapse navbar-ex1-collapse"> 
                <ul class="nav navbar-nav navbar-right">
                 <p class="notice"><%= notice %></p>
                  <p class="alert"><%= alert %></p>
                 <%= form_tag "/posts/search" do %>
                 <%= text_field_tag :search_string %>
                 <%= submit_tag :search %>
                         <% end %>
              </ul>
             
       <% if user_signed_in? %>
           <ul class="nav navbar-nav navbar-right">
             <li><%= link_to 'New Posts', new_post_path %></li>
             <li><%= link_to 'My Account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                <div>Hi! <%= current_user.name %></div>
           </ul>
        <% else %>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          </ul>
         <% end %>
      </nav>
    </div>
    </div>
    </header>
     <div id="main_content" class="container">
        <div id="content" class="col-md-9 center-block">

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-body">

     <div class="form-inputs">
  
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :content %><br>
        <%= f.text_area :content, class: "form-control" %>
      </div>
      <br>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div >

    <h2> <%= link_to post.title, post %></h2><br>
      Submitted <%= time_ago_in_words(post.created_at) %> by <%= post.user.name %>

      <br>
      <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
        Upvote
        <%= post.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
        Downvote
        <%= post.get_downvotes.size %>
        <br>
      <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h1><%= @post.title %></h1>
    <p><strong><%= @post.content %></strong></p>
    <small>Submitted <%= time_ago_in_words(@post.created_at) %> by <%= @post.user.name %></small>
   <br>
    <%= link_to like_post_path(@post), method: :put, class: "btn btn-default btn-sm" do %>
        Upvote
        <%= @post.get_upvotes.size %>
      <% end %>

      <%= link_to dislike_post_path(@post), method: :put, class: "btn btn-default btn-sm" do %>
        Downvote
        <%= @post.get_downvotes.size %>
      <% end %>
      <br>
      <br>

      <div class="panel-footer">
        <strong><%= @post.comments.count %> Comments</strong>
         <br>
         <br>
         <p><%= render @post.comments %></p>
           <br>
           <h3>Reply to Thread</h3>
          <br>
          <%= render "comments/form" %>
          <br>
    <% if (user_signed_in? && (current_user.id == @post.user_id)) %>
      <div class="btn-group">
        <%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
        <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?"}, class:"btn btn-default" %>
      </div>
      </div>
    <% end %>